load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "disk_manager",
    srcs = ["disk_manager.cpp"],
    hdrs = ["disk_manager.hpp"],
    deps = [
        "@com_google_absl//absl/status",
    ],
)
